// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeAnalyzerAPI.Data;

#nullable disable

namespace ResumeAnalyzerAPI.Migrations
{
    [DbContext(typeof(ResumeAnalyzerDbContext))]
    [Migration("20260603020355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ResumeAnalyzerAPI.Models.AnalysisRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("jobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("matchedSkills")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<decimal>("matchedSkillsPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("skills")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<string>("unmatchedSkills")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.HasKey("id");

                    b.ToTable("AnalysisRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
