// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeAnalyzerAPI.Data;

#nullable disable

namespace ResumeAnalyzerAPI.Migrations
{
    [DbContext(typeof(ResumeAnalyzerDbContext))]
    partial class ResumeAnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ResumeAnalyzerAPI.Models.AnalysisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MatchPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedSkills")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<string>("UnmatchedSkills")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.HasKey("Id");

                    b.ToTable("AnalysisRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
